name: home_hustle_app
description: >
  Home Hustle is a mobile app teaching kids financial literacy and entrepreneurship through household chores and community jobs.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.13.6
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  firebase_storage: ^11.5.6
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_local_notifications: ^17.0.0
  flutter_riverpod: ^2.4.9
  flutter_secure_storage: ^9.0.0
  go_router: ^13.0.1
  hooks_riverpod: ^2.4.9
  image_picker: ^1.0.5
  intl: ^0.20.2
  permission_handler: ^11.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
