// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNmTcEp_fpnwS8yUMvNVZrtFnJFlp6amw',
    appId: '1:951763872800:web:4597d08a90d92eb834e045',
    messagingSenderId: '951763872800',
    projectId: 'home-hustle-app',
    authDomain: 'home-hustle-app.firebaseapp.com',
    storageBucket: 'home-hustle-app.firebasestorage.app',
    measurementId: 'G-J0HKPXZBFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4h3Oyiy748dMOGuAd_AqUnahiXgwXixs',
    appId: '1:951763872800:android:5371c28e972a865634e045',
    messagingSenderId: '951763872800',
    projectId: 'home-hustle-app',
    storageBucket: 'home-hustle-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4Krh4mto_NSwS8ELn8n8DRRjyZ6Gr3Ug',
    appId: '1:951763872800:ios:e62548cca9b8b68334e045',
    messagingSenderId: '951763872800',
    projectId: 'home-hustle-app',
    storageBucket: 'home-hustle-app.firebasestorage.app',
    iosBundleId: 'com.example.homeHustleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4Krh4mto_NSwS8ELn8n8DRRjyZ6Gr3Ug',
    appId: '1:951763872800:ios:e62548cca9b8b68334e045',
    messagingSenderId: '951763872800',
    projectId: 'home-hustle-app',
    storageBucket: 'home-hustle-app.firebasestorage.app',
    iosBundleId: 'com.example.homeHustleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNmTcEp_fpnwS8yUMvNVZrtFnJFlp6amw',
    appId: '1:951763872800:web:5b7d16de29b2c18d34e045',
    messagingSenderId: '951763872800',
    projectId: 'home-hustle-app',
    authDomain: 'home-hustle-app.firebaseapp.com',
    storageBucket: 'home-hustle-app.firebasestorage.app',
    measurementId: 'G-WMRD8B8MC6',
  );
}
